
demographics: 
  - participation-by-country
  - gender-breakdown
  - salaries
  - salary-per-country
  - years-of-experience
  - company-size

connections: 
  - connections

# section overview
overview: 
  - overview
  - tools-salary-range
  - tools-company-size
  - tools-years-of-experience
  - happiness

# single tool page
tool: 
  - results-over-time
  - likes
  - dislikes
  - tool-pairing
  - tool-usage-by-country

other-libraries: 
  - other-tools

conclusion: 
  - quadrants

other-tools: 
  - other_languages
  - browser_apis
  - build_tools
  - utility_libraries
  - text_editors
  
opinions: 
  - opinion-js_moving_in_right_direction
  - opinion-building_js_apps_overly_complex
  - opinion-js_over_used_online
  - opinion-enjoy_building_js_apps
  - opinion-would_like_js_to_be_main_lang
  - opinion-js_ecosystem_changing_to_fast
  - opinion-survey_too_long

awards: 
  - highest_satisfaction
  - highest_interest
  - highest_usage
  - most_mentioned
  - prediction
  - special